/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra.dicom;

public class CodecFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CodecFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CodecFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_CodecFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static DataSet load(StreamReader reader, int maxSizeBufferLoad) {
    return new DataSet(imebraJNI.CodecFactory_load(StreamReader.getCPtr(reader), reader, maxSizeBufferLoad), true);
  }

  public CodecFactory() {
    this(imebraJNI.new_CodecFactory(), true);
  }

}
