/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra.dicom;

public class DataHandler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DataHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataHandler(DataHandler right) {
    this(imebraJNI.new_DataHandler(DataHandler.getCPtr(right), right), true);
  }

  public DataHandler assign(DataHandler right) {
    return new DataHandler(imebraJNI.DataHandler_assign(swigCPtr, this, DataHandler.getCPtr(right), right), false);
  }

  public boolean pointerIsValid(int index) {
    return imebraJNI.DataHandler_pointerIsValid(swigCPtr, this, index);
  }

  public void setSize(int elementsNumber) {
    imebraJNI.DataHandler_setSize(swigCPtr, this, elementsNumber);
  }

  public int getSize() {
    return imebraJNI.DataHandler_getSize(swigCPtr, this);
  }

  public int getUnitSize() {
    return imebraJNI.DataHandler_getUnitSize(swigCPtr, this);
  }

  public String getDataType() {
    return imebraJNI.DataHandler_getDataType(swigCPtr, this);
  }

  public char getPaddingByte() {
    return imebraJNI.DataHandler_getPaddingByte(swigCPtr, this);
  }

  public int getSignedLong(int index) {
    return imebraJNI.DataHandler_getSignedLong(swigCPtr, this, index);
  }

  public int getUnsignedLong(int index) {
    return imebraJNI.DataHandler_getUnsignedLong(swigCPtr, this, index);
  }

  public double getDouble(int index) {
    return imebraJNI.DataHandler_getDouble(swigCPtr, this, index);
  }

  public String getString(int index) {
    return imebraJNI.DataHandler_getString(swigCPtr, this, index);
  }

  public void getDate(int index, int[] pYear, int[] pMonth, int[] pDay, int[] pHour, int[] pMinutes, int[] pSeconds, int[] pNanoseconds, int[] pOffsetHours, int[] pOffsetMinutes) {
    imebraJNI.DataHandler_getDate(swigCPtr, this, index, pYear, pMonth, pDay, pHour, pMinutes, pSeconds, pNanoseconds, pOffsetHours, pOffsetMinutes);
  }

  public void setDate(int index, int year, int month, int day, int hour, int minutes, int seconds, int nanoseconds, int offsetHours, int offsetMinutes) {
    imebraJNI.DataHandler_setDate(swigCPtr, this, index, year, month, day, hour, minutes, seconds, nanoseconds, offsetHours, offsetMinutes);
  }

  public void setSignedLong(int index, int value) {
    imebraJNI.DataHandler_setSignedLong(swigCPtr, this, index, value);
  }

  public void setUnsignedLong(int index, int value) {
    imebraJNI.DataHandler_setUnsignedLong(swigCPtr, this, index, value);
  }

  public void setDouble(int index, double value) {
    imebraJNI.DataHandler_setDouble(swigCPtr, this, index, value);
  }

  public void setString(int index, String value) {
    imebraJNI.DataHandler_setString(swigCPtr, this, index, value);
  }

}
