/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra.dicom;

public class DicomDir {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DicomDir(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DicomDir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DicomDir(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DicomDir(DataSet fromDataSet) {
    this(imebraJNI.new_DicomDir(DataSet.getCPtr(fromDataSet), fromDataSet), true);
  }

  public DataSet getDirectoryDataSet() {
    return new DataSet(imebraJNI.DicomDir_getDirectoryDataSet(swigCPtr, this), true);
  }

  public DirectoryRecord getNewRecord() {
    return new DirectoryRecord(imebraJNI.DicomDir_getNewRecord(swigCPtr, this), true);
  }

  public DirectoryRecord getFirstRootRecord() {
    return new DirectoryRecord(imebraJNI.DicomDir_getFirstRootRecord(swigCPtr, this), true);
  }

  public void setFirstRootRecord(DirectoryRecord firstRootRecord) {
    imebraJNI.DicomDir_setFirstRootRecord(swigCPtr, this, DirectoryRecord.getCPtr(firstRootRecord), firstRootRecord);
  }

  public DataSet buildDataSet() {
    return new DataSet(imebraJNI.DicomDir_buildDataSet(swigCPtr, this), true);
  }

}
