/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra.dicom;

public class DirectoryRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DirectoryRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DirectoryRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DirectoryRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DirectoryRecord() {
    this(imebraJNI.new_DirectoryRecord__SWIG_0(), true);
  }

  public DirectoryRecord(DirectoryRecord right) {
    this(imebraJNI.new_DirectoryRecord__SWIG_1(DirectoryRecord.getCPtr(right), right), true);
  }

  public DirectoryRecord assign(DirectoryRecord right) {
    return new DirectoryRecord(imebraJNI.DirectoryRecord_assign(swigCPtr, this, DirectoryRecord.getCPtr(right), right), false);
  }

  public DataSet getRecordDataSet() {
    return new DataSet(imebraJNI.DirectoryRecord_getRecordDataSet(swigCPtr, this), true);
  }

  public DirectoryRecord getNextRecord() {
    return new DirectoryRecord(imebraJNI.DirectoryRecord_getNextRecord(swigCPtr, this), true);
  }

  public DirectoryRecord getFirstChildRecord() {
    return new DirectoryRecord(imebraJNI.DirectoryRecord_getFirstChildRecord(swigCPtr, this), true);
  }

  public DirectoryRecord getReferencedRecord() {
    return new DirectoryRecord(imebraJNI.DirectoryRecord_getReferencedRecord(swigCPtr, this), true);
  }

  public void setNextRecord(DirectoryRecord nextRecord) {
    imebraJNI.DirectoryRecord_setNextRecord(swigCPtr, this, DirectoryRecord.getCPtr(nextRecord), nextRecord);
  }

  public void setFirstChildRecord(DirectoryRecord firstChildRecord) {
    imebraJNI.DirectoryRecord_setFirstChildRecord(swigCPtr, this, DirectoryRecord.getCPtr(firstChildRecord), firstChildRecord);
  }

  public void setReferencedRecord(DirectoryRecord referencedRecord) {
    imebraJNI.DirectoryRecord_setReferencedRecord(swigCPtr, this, DirectoryRecord.getCPtr(referencedRecord), referencedRecord);
  }

  public String getFilePart(int part) {
    return imebraJNI.DirectoryRecord_getFilePart(swigCPtr, this, part);
  }

  public void setFilePart(int part, String partName) {
    imebraJNI.DirectoryRecord_setFilePart(swigCPtr, this, part, partName);
  }

  public String getTypeString() {
    return imebraJNI.DirectoryRecord_getTypeString(swigCPtr, this);
  }

  public void setTypeString(String recordType) {
    imebraJNI.DirectoryRecord_setTypeString(swigCPtr, this, recordType);
  }

  public boolean isNull() {
    return imebraJNI.DirectoryRecord_isNull(swigCPtr, this);
  }

}
