/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra.dicom;

public class DrawBitmap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DrawBitmap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DrawBitmap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DrawBitmap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DrawBitmap(DrawBitmap right) {
    this(imebraJNI.new_DrawBitmap__SWIG_0(DrawBitmap.getCPtr(right), right), true);
  }

  public DrawBitmap(Image sourceImage, TransformsChain transformsChain) {
    this(imebraJNI.new_DrawBitmap__SWIG_1(Image.getCPtr(sourceImage), sourceImage, TransformsChain.getCPtr(transformsChain), transformsChain), true);
  }

  public DrawBitmap assign(DrawBitmap right) {
    return new DrawBitmap(imebraJNI.DrawBitmap_assign(swigCPtr, this, DrawBitmap.getCPtr(right), right), false);
  }

  public int getBitmap(int totalWidthPixels, int totalHeightPixels, int visibleTopLeftX, int visibleTopLeftY, int visibleBottomRightX, int visibleBottomRightY, int[] buffer, int bufferSize) {
    return imebraJNI.DrawBitmap_getBitmap__SWIG_0(swigCPtr, this, totalWidthPixels, totalHeightPixels, visibleTopLeftX, visibleTopLeftY, visibleBottomRightX, visibleBottomRightY, buffer, bufferSize);
  }

  public Memory getBitmap(int totalWidthPixels, int totalHeightPixels, int visibleTopLeftX, int visibleTopLeftY, int visibleBottomRightX, int visibleBottomRightY, Memory reuseMemory) {
    return new Memory(imebraJNI.DrawBitmap_getBitmap__SWIG_1(swigCPtr, this, totalWidthPixels, totalHeightPixels, visibleTopLeftX, visibleTopLeftY, visibleBottomRightX, visibleBottomRightY, Memory.getCPtr(reuseMemory), reuseMemory), true);
  }

}
