/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra.dicom;

public class Stream extends BaseStream {
  private long swigCPtr;

  protected Stream(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.Stream_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Stream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Stream(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Stream() {
    this(imebraJNI.new_Stream__SWIG_0(), true);
  }

  public Stream(Stream right) {
    this(imebraJNI.new_Stream__SWIG_1(Stream.getCPtr(right), right), true);
  }

  public Stream assign(Stream right) {
    return new Stream(imebraJNI.Stream_assign(swigCPtr, this, Stream.getCPtr(right), right), false);
  }

  public void openFileRead(String name) {
    imebraJNI.Stream_openFileRead(swigCPtr, this, name);
  }

  public void openFileWrite(String name) {
    imebraJNI.Stream_openFileWrite(swigCPtr, this, name);
  }

}
