/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra.dicom;

public class StreamReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StreamReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StreamReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_StreamReader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StreamReader(BaseStream stream, int virtualStart, int virtualLength) {
    this(imebraJNI.new_StreamReader__SWIG_0(BaseStream.getCPtr(stream), stream, virtualStart, virtualLength), true);
  }

  public StreamReader(BaseStream stream, int virtualStart) {
    this(imebraJNI.new_StreamReader__SWIG_1(BaseStream.getCPtr(stream), stream, virtualStart), true);
  }

  public StreamReader(BaseStream stream) {
    this(imebraJNI.new_StreamReader__SWIG_2(BaseStream.getCPtr(stream), stream), true);
  }

}
