/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra.dicom;

public class Transform {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Transform(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Transform obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Transform(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Transform(Transform right) {
    this(imebraJNI.new_Transform(Transform.getCPtr(right), right), true);
  }

  public Transform assign(Transform right) {
    return new Transform(imebraJNI.Transform_assign(swigCPtr, this, Transform.getCPtr(right), right), false);
  }

  public boolean isEmpty() {
    return imebraJNI.Transform_isEmpty(swigCPtr, this);
  }

  public Image allocateOutputImage(Image pInputImage, int width, int height) {
    return new Image(imebraJNI.Transform_allocateOutputImage(swigCPtr, this, Image.getCPtr(pInputImage), pInputImage, width, height), true);
  }

  public void runTransform(Image inputImage, int inputTopLeftX, int inputTopLeftY, int inputWidth, int inputHeight, Image outputImage, int outputTopLeftX, int outputTopLeftY) {
    imebraJNI.Transform_runTransform(swigCPtr, this, Image.getCPtr(inputImage), inputImage, inputTopLeftX, inputTopLeftY, inputWidth, inputHeight, Image.getCPtr(outputImage), outputImage, outputTopLeftX, outputTopLeftY);
  }

}
